{{- if .Values.appdynamics.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: appd-db-agent-config
data:
  controller-info.xml: |+
    <controller-info>
        <controller-host>{{ .Values.appdynamics.controller_host }}</controller-host>
        <controller-port>{{ .Values.appdynamics.controller_port }}</controller-port>
        <controller-ssl-enabled>true</controller-ssl-enabled>
        <controller-keystore-password></controller-keystore-password>
        <use-encrypted-credentials></use-encrypted-credentials>
        <credential-store-filename></credential-store-filename>
        <credential-store-password></credential-store-password>
        <use-ssl-client-auth>false</use-ssl-client-auth>
        <asymmetric-keystore-filename></asymmetric-keystore-filename>
        <asymmetric-keystore-password></asymmetric-keystore-password>
        <asymmetric-key-password></asymmetric-key-password>
        <asymmetric-key-alias></asymmetric-key-alias>
        <account-name>{{ .Values.appdynamics.account_name }}</account-name>
        <account-access-key>{{ .Values.appdynamics.account_access_key }}</account-access-key>
    </controller-info>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-db-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appd-db-agent
  template:
    metadata:
      labels:
        name: appd-db-agent
        framework: nodejs
    spec:
      containers:
      - name: appd-db-agent
        {{- if .Values.appdynamics.dbagent_version }}
        image: coolsoxlab/fso-with-coolsox:appd-db-agent-{{.Values.appdynamics.dbagent_version}}
        {{- else }}
        image: coolsoxlab/fso-with-coolsox:appd-db-agent
        {{- end }}
        imagePullPolicy: IfNotPresent
        command: ["/home/appd/db-agent/start-dbagent"]
        args: ["-Ddbagent.name={{ .Values.appdynamics.dbagent_name }}"]
        volumeMounts:
          - name: appd-db-agent-config-volume
            mountPath: /home/appd/db-agent/conf/controller-info.xml
            subPath: controller-info.xml
            readOnly: true
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: no
      volumes:
        - name: appd-db-agent-config-volume
          configMap:
            name: appd-db-agent-config
      {{- if .Values.kubernetes.useImageCredentials}}
      imagePullSecrets:
        - name: container-registry-secret
      {{- end }}
{{- end }}
