{{- if .Values.calisti_istio_gateway.enabled }}
---
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  name: coolsox-mesh-gateway
spec:
  istioControlPlane:
    name: cp-v115x
    namespace: istio-system
  runAsRoot: false
  service:
    ports:
      - name: tcp-status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
    type: LoadBalancer
  type: ingress
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: coolsox-gateway
spec:
  selector:
    gateway-name: coolsox-mesh-gateway
    gateway-type: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coolsox-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - coolsox-gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: front-end
{{- end }}
