{{- if .Values.catalogue.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
    framework: go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
        framework: go
    spec:
      containers:
      - name: catalogue
        {{- if .Values.catalogue.version }}
        image: coolsoxlab/fso-with-coolsox:catalogue-{{.Values.catalogue.version}}
        {{- else }}
        image: coolsoxlab/fso-with-coolsox:catalogue
        {{- end}}
        imagePullPolicy: {{ .Values.kubernetes.imagePullPolicy }}
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: {{ .Values.kubernetes.readOnlyRootFilesystem }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
{{- end }}
