{{- if .Values.payment.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
    framework: go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
  template:
    metadata:
      labels:
        name: payment
        framework: go
    spec:
      containers:
      - name: payment
        {{- if .Values.payment.version }}
        image: coolsoxlab/fso-with-coolsox:payment-{{.Values.payment.version}}
        {{- else }}
        image: coolsoxlab/fso-with-coolsox:payment
        {{- end }}
        imagePullPolicy: {{ .Values.kubernetes.imagePullPolicy }}
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: {{ .Values.kubernetes.readOnlyRootFilesystem }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      {{- if .Values.kubernetes.useImageCredentials}}
      imagePullSecrets:
        - name: container-registry-secret
      {{- end }}
{{- end }}
