{{- if .Values.te_agent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: te-agent
  labels:
    app: thoudsandeyes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thoudsandeyes
  template:
    metadata:
      labels:
        app: thoudsandeyes
    spec:
      hostname: te-agent-{{- .Values.te_agent.agent_name }}
      containers:
       - name: te-agent
         image: 'thousandeyes/enterprise-agent:latest'
         imagePullPolicy: Always
         command:
          - /sbin/my_init
         securityContext:
           capabilities:
             add:
               - NET_ADMIN
               - SYS_ADMIN
         env:
           - name: TEAGENT_ACCOUNT_TOKEN
             valueFrom:
              secretKeyRef:
                name: te-credentials
                key: TEAGENT_ACCOUNT_TOKEN
           - name: TEAGENT_INET
             value: "4"
         resources:
             limits:
               memory: 3584Mi
             requests:
               memory: 2000Mi
      restartPolicy: Always
      {{- if .Values.kubernetes.useImageCredentials}}
      imagePullSecrets:
        - name: container-registry-secret
      {{- end }}
{{- end }}