{{- if .Values.user.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    name: user
    framework: go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user
  template:
    metadata:
      labels:
        name: user
        framework: go
    spec:
      containers:
      - name: user
        {{- if .Values.user.version }}
        image: coolsoxlab/fso-with-coolsox:user-{{.Values.user.version}}
        {{- else }}
        image: coolsoxlab/fso-with-coolsox:user
        {{- end }}
        imagePullPolicy: {{ .Values.kubernetes.imagePullPolicy }}
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 8084
        env:
        - name: MONGO_HOST
          value: user-db:27017
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: {{ .Values.kubernetes.readOnlyRootFilesystem }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 180
          periodSeconds: 3
{{- end }}
